### ISSUE TITLE
Encountered an error (Error: undefined:1:9: property missing ':')

### ISSUE THREAD

**Issue by MiiMan** [jarvis394/geekr#125]
### Describe the problem:
Got an error message at `/company/citymobil/blog/574854`:
```javascript
Error: undefined:1:9: property missing ':'

    at Na (https://habra.vercel.app/static/js/main.cca0c57d.chunk.js:1:38152)
    at div
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2029169
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2011678
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:441583)
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:670973
    at div
    at div
    at div
    at Rr (https://habra.vercel.app/static/js/main.cca0c57d.chunk.js:1:77307)
    at div
    at div
    at vr (https://habra.vercel.app/static/js/main.cca0c57d.chunk.js:1:76305)
    at Li (https://habra.vercel.app/static/js/main.cca0c57d.chunk.js:1:107248)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:9720)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:11768)
    at gu (https://habra.vercel.app/static/js/main.cca0c57d.chunk.js:1:365514)
    at div
    at div
    at c (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:88157)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2136149)
    at t.a (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2028790)
    at Eh (https://habra.vercel.app/static/js/main.cca0c57d.chunk.js:1:434507)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:6323)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:23068)
    at u (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:20135)
    at t.a (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2138254)
```

**Comment by jarvis394** [comment]
Probably won't be fixed, tied to "megapost" realization
