### ISSUE TITLE
При настройке собственной цветовой схемы приложение не работает

### ISSUE THREAD

**Issue by viktorov-aa** [jarvis394/geekr#155]
**Описание бага**
При настройке собственной цветовой схемы приложение не работает

**Шаги для повторения бага**
1.  Создать новую цветовую схему
2. Фон1:  #002b36
   Фон2: #073642
   Текст: #586e75
  Если выставлять текст в RGB, то сразу не падает. Но потом все равно падает.

3. Текст ошибки при создании темы:
`Error: Minified Material-UI error #3; visit https://material-ui.com/production-error/?code=3&args[]=586e75 for the full message.

    at jo (https://geekr.vercel.app/static/js/main.f88dac00.chunk.js:1:145594)
    at t (https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:9729)
    at t (https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:11777)
    at Fu (https://geekr.vercel.app/static/js/main.f88dac00.chunk.js:1:379147)
    at div
    at div
    at c (https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:81266)
    at t (https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:2138491)
    at https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:2028798
    at eb (https://geekr.vercel.app/static/js/main.f88dac00.chunk.js:1:456690)
    at t (https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:6332)
    at t (https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:23076)
    at u (https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:20143)
    at https://geekr.vercel.app/static/js/2.13e09110.chunk.js:2:2140596`
4. Текст ошибки из консоли при применении уже существующей темы. Отображается просто белая страница:
`Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at o (2.13e09110.chunk.js:2)
    at d (2.13e09110.chunk.js:2)
    at body (main.f88dac00.chunk.js:1)
    at Array.onUpdate (2.13e09110.chunk.js:2)
    at e.onUpdate (2.13e09110.chunk.js:2)
    at e.updateOne (2.13e09110.chunk.js:2)
    at e.update (2.13e09110.chunk.js:2)
    at e.update (2.13e09110.chunk.js:2)
    at E (2.13e09110.chunk.js:2)
    at 2.13e09110.chunk.js:2
    at kl (2.13e09110.chunk.js:2)
    at 2.13e09110.chunk.js:2
    at Yi (2.13e09110.chunk.js:2)
    at Dl (2.13e09110.chunk.js:2)
    at gl (2.13e09110.chunk.js:2)
    at 2.13e09110.chunk.js:2
    at 2.13e09110.chunk.js:2
    at Yi (2.13e09110.chunk.js:2)
    at qi (2.13e09110.chunk.js:2)
    at Hi (2.13e09110.chunk.js:2)
    at 2.13e09110.chunk.js:2
    at ke (2.13e09110.chunk.js:2)
    at Fe (2.13e09110.chunk.js:2)
    at 2.13e09110.chunk.js:2
    at Dr (2.13e09110.chunk.js:2)
    at Jt (2.13e09110.chunk.js:2)
    at Zt (2.13e09110.chunk.js:2)
    at 2.13e09110.chunk.js:2
    at Yi (2.13e09110.chunk.js:2)
    at Le (2.13e09110.chunk.js:2)
    at Qt (2.13e09110.chunk.js:2)
    at HTMLDivElement.r (2.13e09110.chunk.js:2)`

**Информация об устройстве:**
 - OS: Win 10
 - Браузер:  Google Chrome
 - Версия браузера: Версия 95.0.4638.69 (Официальная сборка), (64 бит)

**Comment by viktorov-aa** [comment]
Уже должно работать или нет? А то все еще не работает :)

**Comment by jarvis394** [comment]
> Уже должно работать или нет? А то все еще не работает :)

Вы обновили приложение? Нужно нажать на кнопку "Доступно обновление"

Если всё равно не работает, появляется та же ошибка?

**Comment by viktorov-aa** [comment]
Кажется, это косяки кэша браузера. Если открыть в новой вкладке, тема применяется. Если в старой, то даже после нажатия на "обновить" из "Доступно обновление", тема падает

**Comment by viktorov-aa** [comment]
```
DevTools failed to load source map: Could not load content for https://geekr.vercel.app/static/js/2.13e09110.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://geekr.vercel.app/static/js/main.f88dac00.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Добавились в консоли ошибки. Они мне ни о чем не говорят.

PS
В новой вкладке темы работают нормально, так что думаю, что issue можно обратно закрыть )

**Comment by jarvis394** [comment]
🥳

**Comment by viktorov-aa** [comment]
Блин, кажется, я поторопился. Теперь понимаю еще меньше. В одной вкладке работает, в двух других не работает. Зря я открыл несколько вкладок? Кажется, я схожу с ума :)

**Comment by jarvis394** [comment]
> В одной вкладке работает, в двух других не работает.

Это проделки service-worker'a. Закройте все вкладки с приложением и откройте заново. Если открыто несколько вкладок, SW не может у всех обновиться.

**Comment by viktorov-aa** [comment]
Удалил все куки. Закрыл вкладки, открыл. Все в порядке.  Спасибо!

PS
Если добавите в дефолтные темы Solaeized Dark и Solarized Light будет просто идеально.
https://ethanschoonover.com/solarized/

**Comment by jarvis394** [comment]
![image](https://user-images.githubusercontent.com/37776763/140611278-82c2feab-cbe3-472b-a1ee-1334bf96d33f.png)

![image](https://user-images.githubusercontent.com/37776763/140611256-9814ebdf-e271-49e4-a503-dd771af0a9f4.png)

такого плана?

**Comment by viktorov-aa** [comment]
Ага, такого :)
