### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/geekr#176]
**Описание бага**
Не работает

**Шаги для повторения бага**
1. Открыть хабра

**Скриншоты**
![Screenshot_20220421_093238_com.android.chrome.jpg](https://user-images.githubusercontent.com/26829359/164360151-c3ce0496-2443-459b-b098-8148df3d4d5f.jpg)

```
TypeError: Cannot read properties of undefined (reading 'map')

    at Mp (https://geekr.vercel.app/static/js/main.d34baa04.chunk.js:1:354235)
    at t (https://geekr.vercel.app/static/js/2.c1900950.chunk.js:2:9729)
    at t (https://geekr.vercel.app/static/js/2.c1900950.chunk.js:2:11777)
    at Fu (https://geekr.vercel.app/static/js/main.d34baa04.chunk.js:1:380128)
    at div
    at div
    at c (https://geekr.vercel.app/static/js/2.c1900950.chunk.js:2:81266)
    at t (https://geekr.vercel.app/static/js/2.c1900950.chunk.js:2:2138491)
    at t.a (https://geekr.vercel.app/static/js/2.c1900950.chunk.js:2:2028798)
    at eb (https://geekr.vercel.app/static/js/main.d34baa04.chunk.js:1:457671)
    at t (https://geekr.vercel.app/static/js/2.c1900950.chunk.js:2:6332)
    at t (https://geekr.vercel.app/static/js/2.c1900950.chunk.js:2:23076)
    at u (https://geekr.vercel.app/static/js/2.c1900950.chunk.js:2:20143)
    at t.a (https://geekr.vercel.app/
```

**Comment by jarvis394** [comment]
На какой странице сайта происходит проблема?

**Comment by centralhardware** [comment]
На главной, просто домен без путей открываешь и вываливается ошибка

**Comment by jarvis394** [comment]
> На главной, просто домен без путей открываешь и вываливается ошибка

Странно, у меня все работает 🤔
Можете рассказать:
- редиректит ли после захода на рутовый путь (https://geekr.vercel.app)
- путь на который редиректит сайт после захода
- был выполнен вход в аккаунт или нет

**Comment by centralhardware** [comment]
Возможно это из-за того что я был щалогинен в аккаунт который сейчас удален

**Comment by centralhardware** [comment]
С главное делает редирект на all/p/1

**Comment by centralhardware** [comment]
Да, из браузера смог выйти и ошибка ушла все нормально грузиться
