### ISSUE TITLE
Падает при переключении потоков лучших за сутки-неделя-сутки

### ISSUE THREAD

**Issue by tsunamaru** [jarvis394/geekr#191]
**Описание бага**
```
Произошла ошибка

[Нажми сюда](https://geekr.vercel.app/), чтобы вернуться домой. Эта ошибка записана в логи Sentry и будет обработана в ближайшее время.

Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at Zo (https://geekr.vercel.app/static/js/main.ae8486ad.chunk.js:1:180102)
    at ul
    at https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:2066147
    at https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:2015810
    at div
    at Er (https://geekr.vercel.app/static/js/main.ae8486ad.chunk.js:1:80643)
    at div
    at div
    at Mp (https://geekr.vercel.app/static/js/main.ae8486ad.chunk.js:1:354426)
    at t (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:9729)
    at t (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:11777)
    at Fu (https://geekr.vercel.app/static/js/main.ae8486ad.chunk.js:1:380379)
    at div
    at div
    at c (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:81266)
    at t (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:2142615)
    at t.a (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:2032922)
    at eb (https://geekr.vercel.app/static/js/main.ae8486ad.chunk.js:1:457922)
    at t (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:6332)
    at t (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:23076)
    at u (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:20143)
    at t.a (https://geekr.vercel.app/static/js/2.e4c26870.chunk.js:2:2144720)
```

**Шаги для повторения бага**
1. Открыть https://[geekr.](https://geekr.vercel.app/top/daily/p/1)vercel.app/top/daily/p/1
2. Переключится на неделю
3. Переключится обратно на сутки

**Информация об устройстве:**
 - OS: MacOS
 - Браузер: Microsoft Edge
 - Версия браузера: [последняя]

**Комментарий**
Аналогичный краш происходит при других вариациях, например сутки-месяц-сутки, сутки-месяц-неделя-сутки и так далее.

**Comment by jarvis394** [comment]
Макось и Edge, интересная комбинация 🙃

У себя не получилось воспроизвести, скорее всего теги к Технотексту добавили новые и у меня приложение не особо умное к таким нововведениям :/

**Comment by centralhardware** [comment]
Движок один фиг от сафари, у меня на айфоне вообще не работает перешел на ванильный Хабр

**Comment by tsunamaru** [comment]
Уже не воспроизводится, проблема была несколько часов.

> Движок один фиг от сафари

Ты с ios поделием путаешь
